

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 'URL Validation'
        uses: peterekepeter/test-with-browser@main
        with:
          url: 'garbagevalue'
          expect-error: true
      - name: 'Minimal Setup'
        uses: peterekepeter/test-with-browser@main
        with:
          url: 'https://github.com/status'
      - uses: actions/checkout@v4
      - name: 'Static File'
        uses: peterekepeter/test-with-browser@main
        with:
          url: 'file://${{ github.workspace }}/test/static-site/index.html'
      - name: 'Firefox'
        uses: peterekepeter/test-with-browser@main
        with:
          url: 'file://${{ github.workspace }}/test/static-site/index.html'
          browser: 'firefox'
