

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # todo find a way to test this
    # - name: 'Timeout failure'
    #   uses: peterekepeter/test-with-browser@main
    #   with:
    #     url: 'https://github.com/status'
    #     timeout-seconds: 0.001
    #     timeout-inactive-seconds: 0.001
    #     expect-fail: true
    - name: 'Static file not found'
      uses: peterekepeter/test-with-browser@main
      with:
        url: 'file://${{ github.workspace }}/test/doesnotexist'
        expect-fail: true
    - name: 'URL Validation'
      uses: peterekepeter/test-with-browser@main
      with:
        url: 'garbagevalue'
        expect-fail: true
    - name: 'Expect console pattern not matches'
      uses: peterekepeter/test-with-browser@main
      with:
        url: 'file://${{ github.workspace }}/test/hello.html'
        expect-console-pattern: 'shoud_not_match_anything'
        expect-fail: true
    - name: 'Expect console pattern matches'
      uses: peterekepeter/test-with-browser@main
      with:
        url: 'file://${{ github.workspace }}/test/test.html'
        expect-console-pattern: '\d+ tests successfully passed!'
    - name: 'URL Validation'
      uses: peterekepeter/test-with-browser@main
      with:
        url: 'garbagevalue'
        expect-fail: true
    - name: 'Minimal Setup'
      uses: peterekepeter/test-with-browser@main
      with:
        url: 'https://github.com/status'
    - name: 'Static File'
      uses: peterekepeter/test-with-browser@main
      with:
        url: 'file://${{ github.workspace }}/test/hello.html'
    - name: 'Firefox'
      uses: peterekepeter/test-with-browser@main
      with:
        url: 'file://${{ github.workspace }}/test/hello.html'
        browser: 'firefox'
